owner: WeilNET
repo: uptime

sites:
  - name: Infrastructure - AMS0
    check: "tcp-ping"
    url: $ENDPOINT_AMS0
    port: 9100
  - name: Infrastructure - SKP1
    check: "tcp-ping"
    url: $ENDPOINT_SKP1
    port: 5678

status-website:
  cname: status.weilnet.org
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Weilnet uptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: A status page.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
